"use client";

import { useParams } from "next/navigation";
import { ShieldCheck, TriangleAlert } from "lucide-react";
import { PrivateShell } from "@/components/templates/private-shell";
import { usePreferredLocale } from "@/shared/lib/locale";

export default function SafetyPage() {
  const params = useParams();
  const locale = usePreferredLocale("private", (params?.locale as string) || "en");
  const isPt = locale === "pt";
  return <PrivateShell><main className="safety-page"><span className="safety-kicker">NOVA RECOVERY</span><h1>{isPt ? "Segurança e limites" : "Safety & limitations"}</h1><p className="safety-lead">{isPt ? "A NOVA organiza informação autorrelatada e educação. Não é uma avaliação médica." : "NOVA organizes self-reported information and education. It is not a medical assessment."}</p><div className="safety-grid"><section><ShieldCheck size={22}/><h2>{isPt ? "O que a NOVA faz" : "What NOVA does"}</h2><ul>{(isPt ? ["Organiza sintomas, atividades e funcionamento diário.", "Mostra mudanças nas tuas próprias entradas.", "Ajuda a preparar conversas com profissionais.", "Apresenta informação educativa baseada em fontes."] : ["Organizes symptoms, activities and daily functioning.", "Shows changes in your own entries.", "Helps prepare conversations with professionals.", "Provides education based on cited sources."]).map((item) => <li key={item}>{item}</li>)}</ul></section><section><TriangleAlert size={22}/><h2>{isPt ? "O que a NOVA não faz" : "What NOVA does not do"}</h2><ul>{(isPt ? ["Não diagnostica concussão ou outras condições.", "Não prescreve tratamento.", "Não confirma recuperação nem determina prontidão.", "Não fornece autorização médica nem substitui um profissional."] : ["Does not diagnose concussion or other conditions.", "Does not prescribe treatment.", "Does not confirm recovery or determine readiness.", "Does not provide medical clearance or replace a professional."]).map((item) => <li key={item}>{item}</li>)}</ul></section></div><section className="care-notice"><h2>{isPt ? "Quando procurar cuidados" : "When to seek care"}</h2><p>{isPt ? "Procura avaliação médica quando houver preocupação, sintomas persistentes ou agravamento. Em emergência, contacta os serviços locais de emergência. Não esperes pela NOVA." : "Seek medical care when you are concerned, symptoms persist, or symptoms worsen. In an emergency, contact local emergency services. Do not wait for NOVA."}</p></section></main><style jsx>{`.safety-page{max-width:980px;margin:0 auto;padding:12px 20px 48px}.safety-kicker{color:#00d2b5;font-size:.7rem;font-weight:800;letter-spacing:.14em}.safety-page h1{margin:8px 0;font-size:2.1rem}.safety-lead{color:rgba(255,255,255,.65);margin-bottom:24px}.safety-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.safety-grid section,.care-notice{padding:24px;border:1px solid rgba(255,255,255,.1);border-radius:12px;background:#0a0e1a}.safety-grid svg{color:#00d2b5}.safety-grid section:nth-child(2) svg{color:#f59e0b}.safety-grid h2,.care-notice h2{font-size:1.1rem;margin:14px 0}.safety-grid ul{display:grid;gap:10px;margin:0;padding-left:20px;color:rgba(255,255,255,.7);line-height:1.5}.care-notice{margin-top:18px;border-color:rgba(245,158,11,.35)}.care-notice p{color:rgba(255,255,255,.7);line-height:1.6}@media(max-width:700px){.safety-grid{grid-template-columns:1fr}}`}</style></PrivateShell>;
}